version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:latest
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
      - ./src/main/resources/liquibase.properties:/liquibase/liquibase.properties
    command: >
      bash -c "sleep 10 &&
      /liquibase/liquibase
      --changeLogFile=/liquibase/changelog/changelog-master.yaml
      --url=jdbc:postgresql://postgres:5432/citizix_db
      --username=citizix_user
      --password=S3cret
      --classpath=/liquibase/changelog
      --driver=org.postgresql.Driver
      --logLevel=debug
      update"
  app:
    container_name: app
    image: cp:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/secrets.yaml:/app/secrets.yaml
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_LOCATION=/app/secrets.yaml
    command: >
      bash -c "sleep 20 &&
      java -jar /app/app.jar"