version: '3.9'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db