spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citizix_db
    username: citizix_user
    password: S3cret
secret.key: "S3cret"
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: qwerty
    key-alias: tomcat
    key-password: qwerty
